name: "FACTORY MAIN WORKFLOW"

on:
  workflow_dispatch:

jobs:
  build:
    env:
      GO111MODULE: "on"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d")"

      - name: setting up build environment
        run: |
          sudo mkdir /artifacts
          sudo chmod 777 /artifacts
          sudo apt update
          sudo apt install -y make gcc python3-dev python3-pip wget curl
          wget -q https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz
          echo /usr/local/go/bin >> $GITHUB_PATH

      - name: building "projectdiscovery/subfinder"
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          cd ~/go/bin && zip /artifacts/subfinder_linux_amd64.zip subfinder

      - name: building "projectdiscovery/httpx"
        run: |
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          cd ~/go/bin && zip /artifacts/httpx_linux_amd64.zip httpx

      - name: building "projectdiscovery/nuclei"
        run: |
          go install -v github.com/projectdiscovery/nuclei/cmd/nuclei@latest
          cd ~/go/bin && zip /artifacts/nuclei_linux_amd64.zip nuclei

      - name: building "projectdiscovery/shuffledns"
        run: |
          go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest
          cd ~/go/bin && zip /artifacts/shuffledns_linux_amd64.zip shuffledns

      - name: building "d3mondev/puredns"
        run: |
          go install github.com/d3mondev/puredns/v2@latest
          cd ~/go/bin && zip /artifacts/puredns_linux_amd64.zip puredns

      - name: building "ffuf/ffuf"
        run: |
          go get -u github.com/ffuf/ffuf
          cd ~/go/bin && zip /artifacts/ffuf_linux_amd64.zip ffuf

      - name: building "blechschmidt/massdns"
        run: |
          git clone --depth 1 https://github.com/blechschmidt/massdns
          cd massdns
          make && cd bin
          zip /artifacts/massdns_linux_amd64.zip massdns

      - name: building "robertdavidgraham/masscan"
        run: |
          git clone --depth 1 https://github.com/robertdavidgraham/masscan && cd masscan
          make && cd ./bin && zip /artifacts/masscan_linux_amd64.zip masscan

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            /artifacts/*